---
title: Results - KS Test
output: html_document
---

<br>

```{r, include = FALSE, warning = FALSE, message = FALSE }
source("../R/update-results.R")
#Set update = TRUE to update results from source code
update_results(update = FALSE)
source("../results/results-setup.R")
```

# Method Comparison

```{r, compare-all-lmm-theoretical, echo = FALSE, message = FALSE, warning = FALSE, fig.height = 10, fig.cap = "LMM, theoretical"}

histogram.err.pow(df = pvals, Type = "LMM", ResType = TRUE )

```

```{r, compare-all-lmm-estimated, echo = FALSE, message = FALSE, warning = FALSE, fig.height = 10, fig.cap = "LMM, estimated"}

histogram.err.pow(df = pvals, Type = "LMM", ResType = FALSE)

```

```{r, compare-all-glmm-theoretical, echo = FALSE, message = FALSE, warning = FALSE, fig.height = 10, fig.cap = "GLMM, theoretical"}

histogram.err.pow(df = pvals, Type = "GLMM", ResType = TRUE )

```

```{r, compare-all-glmm-estimated, echo = FALSE, message = FALSE, warning = FALSE, fig.height = 10, fig.cap = "GLMM, estimated"}

histogram.err.pow(df = pvals, Type = "GLMM", ResType = FALSE)

```

\clearpage
\newpage
# Compound Symmetry Covariance Structure
## Linear Mixed Model

```{r, simpleGLMM-results-LMM-all, echo = FALSE, message = FALSE, warning = FALSE, fig.height = 10, fig.cap = "Linear Mixed Model. Type I Error for the correctly specified (A) model and Power for mis-specified (B-D) models evaluated under four different tests: Anderson-Darling GOF, Kolmogorov-Smirnov (GOF), Analysis of Variance, and Levene's Test of Equal Variance for each method. Mis-specifications from left to right are: Missing Random Effect (B), Missing Covariate (C), and Mis-specified Random Effect (D). Colors represent theorerical (blue) and estimated (red) residuals."}

res.methods <- c(
   'full Gaussian',
   'one-step Gaussian',
   'one-step Generic',
   'cdf',
   'MCMC',
   'Pearson',
   "Unconditional ecdf, Not Rotated", 
   "Conditional ecdf, Not Rotated",
   "Unconditional ecdf, Rotated", 
   "Conditional ecdf, Rotated"
)


pval.all <- filter.all(df = pvals, 
                       mod = "simpleGLMM", 
                       type_ = "LMM", 
                       res.methods)

pval.all$test <- factor(pval.all$test,
                        levels = c( "GOF.ad",
                                    "GOF.ks",
                                    "GOF.lf",
                                    "outlier",
                                    "AOV",
                                    "EqVar"),
                        labels = c("Anderson-Darling GOF",
                                   "Kolmogorov-Smirnov GOF",
                                   "Lilliefors GOF",
                                   "outlier",
                                   "Analysis of Variance",
                                   "Levene's Test of Equal Variance"))

pval.all$misp <- factor(pval.all$misp,
         levels = c( "correct", 
                     "missre", 
                     "missunifcov", 
                     "mispre"),
         labels = c("A: Correct",
                    "B: Miss RE",
                    "C: Miss Uniform X",
                    "D: Misp. RE" ))
plot.err.pow(pval.all)
```


## Generalized Linear Mixed Model
```{r, simpleGLMM-results-GLMM-all, echo = FALSE, message = FALSE, warning = FALSE, fig.height = 10, fig.cap = "Generalized Linear Mixed Model. Type I Error for the correctly specified (A) model and Power for mis-specified (B-D) models evaluated under four different tests: Anderson-Darling GOF, Kolmogorov-Smirnov (GOF), Analysis of Variance, and Levene's Test of Equal Variance for each method. Mis-specifications from left to right are: Missing Random Effect (B), Negative Binomal fit with a Poisson (C), and Mis-specified Random Effect (D). Colors represent theorerical (blue) and estimated (red) residuals."}

res.methods <- c(
   'full Gaussian',
   'one-step Gaussian',
   'one-step Generic',
   'cdf',
   'MCMC',
   'Pearson',
   "Unconditional ecdf, Not Rotated", 
   "Conditional ecdf, Not Rotated",
   "Unconditional ecdf, Rotated", 
   "Conditional ecdf, Rotated"
)


pval.all <- filter.all(df = pvals, 
                       mod = "simpleGLMM", 
                       type_ = "GLMM", 
                       res.methods)

pval.all$test <- factor(pval.all$test,
                        levels = c( "GOF.ad",
                                    "GOF.ks",
                                    "GOF.lf",
                                    "outlier",
                                    "AOV",
                                    "EqVar"),
                        labels = c("Anderson-Darling GOF",
                                   "Kolmogorov-Smirnov GOF",
                                   "Lilliefors GOF",
                                   "outlier",
                                   "Analysis of Variance",
                                   "Levene's Test of Equal Variance"))

pval.all$misp <- factor(pval.all$misp,
         levels = c( "correct", 
                     "missre", 
                     "nb-pois", 
                     "mispre"),
         labels = c("A: Correct",
                    "B: Miss RE",
                    "C: NBinom - Pois",
                    "D: Misp. RE" ))
plot.err.pow(pval.all)
```

\clearpage
\newpage
# Temporal Covariance Structure: Randomwalk
## Linear Mixed Model
```{r, randomwalk-results-LMM-all, echo = FALSE, message = FALSE, warning = FALSE, fig.height = 10, fig.cap = "Randomwalk, Linear Mixed Model. Type I Error for the correctly specified (A) model and Power for mis-specified (B-E) models evaluated under three different tests: Anderson-Darling GOF, Kolmogorov-Smirnov GOF, and Autocorrelation test for each method. Mis-specifications from left to right are: Missing Random Effect (B), Heterosckedacity (C), Missing Drift Term (D), and Mis-specified Random Effect (E). Colors represent theorerical (blue) and estimated (red) residuals."}

res.methods <- c(
   'full Gaussian',
   'one-step Gaussian',
   'one-step Generic',
   'cdf',
   'MCMC',
   'Pearson',
   "Unconditional ecdf, Not Rotated", 
   "Conditional ecdf, Not Rotated",
   "Unconditional ecdf, Rotated", 
   "Conditional ecdf, Rotated"
)


pval.all <- filter.all(df = pvals, 
                       mod = "randomwalk", 
                       type_ = "LMM", 
                       res.methods)

pval.all$test <- factor(pval.all$test,
                        levels = c( "GOF.ad",
                                    "GOF.ks",
                                    "GOF.lf",
                                    "outlier",
                                    "Auto"  ),
                        labels = c("Anderson-Darling GOF",
                                   "Kolmogorov-Smirnov GOF",
                                   "Lilliefors GOF",
                                   "outlier",
                                   "Autocorrelation Test"))

pval.all$misp <- factor(pval.all$misp,
         levels = c( "correct", 
                     "missre", 
                     "hsk",
                     "mu0",
                     "mispre"),
         labels = c("A: Correct",
                    "B: Miss RE",
                    "C: Heterosk.",
                    "D: Miss Drift",
                    "E: Misp. RE"))
plot.err.pow(pval.all)
```

```{r, randomwalk-results-GLMM-all, echo = FALSE, message = FALSE, warning = FALSE, fig.height = 10, fig.cap = "Randomwalk, Generalized Linear Mixed Model. Type I Error for the correctly specified (A) model and Power for mis-specified (B-E) models evaluated under three different tests: Anderson-Darling GOF, Kolmogorov-Smirnov GOF, and Autocorrelation test for each method. Mis-specifications from left to right are: Missing Random Effect (B), Gamma fit with Normal (C), Missing Drift Term (D), and Mis-specified Random Effect (E). Colors represent theorerical (blue) and estimated (red) residuals."}

res.methods <- c(
   'full Gaussian',
   'one-step Gaussian',
   'one-step Generic',
   'cdf',
   'MCMC',
   'Pearson',
   "Unconditional ecdf, Not Rotated", 
   "Conditional ecdf, Not Rotated",
   "Unconditional ecdf, Rotated", 
   "Conditional ecdf, Rotated"
)


pval.all <- filter.all(df = pvals, 
                       mod = "randomwalk", 
                       type_ = "GLMM", 
                       res.methods)

pval.all$test <- factor(pval.all$test,
                        levels = c( "GOF.ad",
                                    "GOF.ks",
                                    "GOF.lf",
                                    "outlier",
                                    "Auto"  ),
                        labels = c("Anderson-Darling GOF",
                                   "Kolmogorov-Smirnov GOF",
                                   "Lilliefors GOF",
                                   "outlier",
                                   "Autocorrelation Test"))

pval.all$misp <- factor(pval.all$misp,
         levels = c( "correct", 
                     "missre", 
                     "gamma-normal",
                     "mu0",
                     "mispre"),
         labels = c("A: Correct",
                    "B: Miss RE",
                    "C: Heterosk.",
                    "D: Miss Drift",
                    "E: Misp. RE"))
plot.err.pow(pval.all)
```

\clearpage
\newpage
# Spatial Covariance Structure
## Linear Mixed Model

```{r, spatialM-results-LMM-all, echo = FALSE, message = FALSE, warning = FALSE, fig.height = 10, fig.cap = "Spatial Linear Mixed Model. Type I Error for the correctly specified (A) model and Power for mis-specified (B-D) models evaluated under three different tests: Anderson-Darling GOF, Kolmogorov-Smirnov (GOF), and Moran's I Spatial Correlation Test for each method. Mis-specifications from left to right are: Missing Random Effect (B), Lognormal Error (C), and Mis-specified Random Effect (D). Colors represent theorerical (blue) and estimated (red) residuals."}

res.methods <- c(
   'full Gaussian',
   'one-step Gaussian',
   'one-step Generic',
   'cdf',
   'MCMC',
   'Pearson',
   "Unconditional ecdf, Not Rotated", 
   "Conditional ecdf, Not Rotated",
   "Unconditional ecdf, Rotated", 
   "Conditional ecdf, Rotated"
)


pval.all <- filter.all(df = pvals, 
                       mod = "spatial", 
                       type_ = "LMM", 
                       res.methods)

pval.all$test <- factor(pval.all$test,
                        levels = c( "GOF.ad",
                                    "GOF.ks",
                                    "GOF.lf",
                                    "outlier",
                                    "SAC"),
                        labels = c("Anderson-Darling GOF",
                                   "Kolmogorov-Smirnov GOF",
                                   "Lilliefors GOF",
                                   "outlier",
                                   "Moran's I Spatial Autocorrelation"))

pval.all$misp <- factor(pval.all$misp,
         levels = c( "correct", 
                     "missre", 
                     "ln-error", 
                     "mispre"),
         labels = c("A: Correct",
                    "B: Miss RE",
                    "C: Lognormal Error",
                    "D: Misp. RE" ))
plot.err.pow(pval.all)
```

## Generalized Linear Mixed Model

```{r, spatialM-results-GLMM-all, echo = FALSE, message = FALSE, warning = FALSE, fig.height = 10, fig.cap = "Spatial Generalized Linear Mixed Model. Type I Error for the correctly specified (A) model and Power for mis-specified (B-D) models evaluated under three different tests: Anderson-Darling GOF, Kolmogorov-Smirnov (GOF), and Moran's I Spatial Correlation Test for each method. Mis-specifications from left to right are: Missing Random Effect (B), Zero-Inflated Poisson fit to a Poisson (C), and Mis-specified Random Effect (D). Colors represent theorerical (blue) and estimated (red) residuals."}

res.methods <- c(
   'full Gaussian',
   'one-step Gaussian',
   'one-step Generic',
   'cdf',
   'MCMC',
   'Pearson',
   "Unconditional ecdf, Not Rotated", 
   "Conditional ecdf, Not Rotated",
   "Unconditional ecdf, Rotated", 
   "Conditional ecdf, Rotated"
)


pval.all <- filter.all(df = pvals, 
                       mod = "spatial", 
                       type_ = "GLMM", 
                       res.methods)

pval.all$test <- factor(pval.all$test,
                        levels = c( "GOF.ad",
                                    "GOF.ks",
                                    "GOF.lf",
                                    "outlier",
                                    "SAC"),
                        labels = c("Anderson-Darling GOF",
                                   "Kolmogorov-Smirnov GOF",
                                   "Lilliefors GOF",
                                   "outlier",
                                   "Moran's I Spatial Autocorrelation"))

pval.all$misp <- factor(pval.all$misp,
         levels = c( "correct", 
                     "missre", 
                     "pois-zip", 
                     "mispre"),
         labels = c("A: Correct",
                    "B: Miss RE",
                    "C: Zip - Pois",
                    "D: Misp. RE" ))
plot.err.pow(pval.all)
```
