---
title: "Results - MLEs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE, warning = FALSE, message = FALSE }
source("../R/update-results.R")
#Set update = TRUE to update results from source code
update_results(update = FALSE)
source("../results/results-setup.R")
```

```{r, rename-values, include = FALSE, warning = FALSE, message = FALSE}
mles$misp <- factor(mles$misp,
                    levels = c(
                      "correct", 
                      "overdispersion", 
                      "gamma-normal",
                      "hsk",
                      "nb-pois",
                      "missunifcov",
                      "pois-zip",
                      "ln-error",
                      "missre",
                      "mu0",
                      "mispre"
                    ),
                    labels = c(
                      "Correct", 
                      "Overdispersion", 
                      "Gamma - Normal",
                      "Hsk",
                      "NB-Pois",
                      "Missing Covariate",
                      "Pois-ZIP",
                      "Lognormal Error",
                      "Missing RE",
                      "Missing Drift",
                      "Miss-specified RE"
                    )
            )
mles$par[mles$model == 'simpleGLMM' & mles$type == 'LMM' & mles$par == 'beta'] <- "beta_1"

mles$par <- factor(mles$par,
                   levels = c(
                     "mu",
                     "beta", 
                     "beta_1", 
                     "beta_2",   
                     "theta",
                     "ln_sig_y",  
                     "ln_sig_u", 
                     "ln_kappa",
                     "ln_tau"
                   ),
                   labels = c(
                     expression(mu),
                     expression(beta[0]), 
                     expression(beta[0]), 
                     expression(beta[1]),   
                     "size",
                     expression("ln("~sigma[y]~")"),  
                     expression("ln("~sigma[u]~")"), 
                     expression("ln("~kappa~")"), 
                     expression("ln("~tau~")")
                   ))
 
```

## Linear Model
```{r, echo = FALSE, fig.cap = "Bias in parameter estimates for the linear model when the model is correctly specified across 1000 simulations."}

mle.df <- dplyr::filter(mles, model == 'linmod')

plot.mles(mle.df) 
```

## Mixed Model

### LMM
```{r, echo = FALSE, fig.cap = "Bias in parameter estimates for the linear mixed model with a uniform covariate when the model is correctly specified across 1000 simulations."}
mle.df <- dplyr::filter(mles, model == 'simpleGLMM' & type == 'LMM')
plot.mles(mle.df)
```

### GLMM
```{r, echo = FALSE, fig.cap = "Bias in parameter estimates for the generalized linear mixed model with a negative binomial distribution when the model is correctly specified across 1000 simulations."}
mle.df <- dplyr::filter(mles, model == 'simpleGLMM' & type == 'GLMM')

plot.mles(mle.df) 
```


## Randomwalk

### LMM
```{r, echo = FALSE, fig.cap = "Bias in parameter estimates for the randomwalk model with a drift term when the model is correctly specified across 1000 simulations."}
mle.df <- dplyr::filter(mles, model == 'randomwalk' & type == 'LMM')

plot.mles(mle.df)
```

### GLMM
```{r, echo = FALSE, fig.cap = "Bias in parameter estimates for the Gamma distributed randomwalk model with a drift term when the model is correctly specified across 1000 simulations."}
mle.df <- dplyr::filter(mles, model == 'randomwalk' & type == 'GLMM')

plot.mles(mle.df)
```


## Spatial
### LMM
```{r, echo = FALSE, fig.cap = "Bias in parameter estimates for the spatial linear mixed model when the model is correctly specified across 1000 simulations."}
mle.df <- dplyr::filter(mles, model == 'spatial' & type == 'LMM')

plot.mles(mle.df) 
```


### GLMM
```{r, echo = FALSE, fig.cap = "Bias in parameter estimates for the spatial Poisson model when the model is correctly specified across 1000 simulations."}
mle.df <- dplyr::filter(mles, model == 'spatial' & type == 'GLMM')

plot.mles(mle.df)
```
