---
title: Table Placeholders
output: 
  pdf_document:
    extra_dependencies: ["booktabs", "pdflscape"]
---

# Methods

```{r, include = FALSE, warning = FALSE, message = FALSE }
source("../../results/results-setup.R")
```


\input{"tables/linmod-specs.tex"}

\input{"tables/simpleGLMM-specs.tex"}

\input{"tables/randomwalk-specs.tex"}

\input{"tables/spatial-specs.tex"}

```{=tex}
\clearpage
\newpage
```
# Results

## Linear Model

```{r, linmod-results-theor, echo = FALSE, message = FALSE, fig.width = 8, warning = FALSE}
res.methods <- c(
   'full Gaussian',
   'one-step Gaussian',
   'one-step Generic',
   'cdf',
   'MCMC',
   'Unconditional ecdf, Rotated',
   'Unconditional ecdf, Not Rotated',
   'Conditional ecdf, Rotated',  
   'Conditional ecdf, Not Rotated',
   'Pearson'
)

pval.df.true <- filter.true(pvals, "linmod",
                            type_ = "LMM",
                            test_ = "GOF.ks",
                            method.vec = res.methods)
pval.df.est <- filter.est(pvals, "linmod",
                          type_ = "LMM",
                          test_ = "GOF.ks",
                          method.vec = res.methods)

pval.df.true$misp <- factor(pval.df.true$misp,
         levels = c("correct", "overdispersion"),
         labels = c("Correct", "Overdispersion"))
pval.df.est$misp <- factor(pval.df.est$misp,
         levels = c("correct", "overdispersion"),
         labels = c("Correct", "Overdispersion"))

tbl.err.pow(pval.df.true, 
        caption = "Linear Model. Type I error rates and Power evaluated for each analytical and simulation method for theoretical residuals using the KS normality test. Results are partitioned out by residual type (top to bottom).")
```

```{r, linmod-results-est, echo = FALSE, message = FALSE, fig.width = 8, warning = FALSE}

tbl.err.pow(pval.df.est, 
        caption = "Linear Model. Type I error rates and Power evaluated for each analytical and simulation method for estimated residuals using the KS normality test. Results are partitioned out by residual type (top to bottom).")
```

```{=tex}
\clearpage
\newpage
```

## Mixed Model

```{r, simpleGLMM-results-theor, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 8}

pval.df.true <- filter.true(pvals, 
                            "simpleGLMM",
                            type_ = "LMM",
                            test_ = "GOF.ks",
                             method.vec = res.methods)
pval.df.est <- filter.est(pvals, 
                            "simpleGLMM",
                            type_ = "LMM",
                            test_ = "GOF.ks",
                             method.vec = res.methods)

pval.df.true$misp <- factor(pval.df.true$misp,
         levels = c('correct', 'missre', 'missunifcov', 'mispre'),
         labels = c("Correct",
                    "A: Missing RE",
                    "B: Missing X",
                    "C: Misp RE" ))


pval.df.est$misp <- factor(pval.df.est$misp,
          levels = c('correct', 'missre', 'missunifcov', 'mispre'),
         labels = c("Correct",
                    "A: Missing RE",
                    "B: Missing X",
                    "C: Misp RE" ))

tbl.err.pow(pval.df.true, 
        caption = "Mixed Model. Type I error rates and Power evaluated for each analytical and simulation method for theoretical residuals using the KS normality test. Results are partitioned out by model mis-specification (from left to right) and residual type (top to bottom).")
```

```{r, simpleGLMM-results-est, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 8}

tbl.err.pow(pval.df.est, 
        caption = "Mixed Model. Type I error rates and Power evaluated for each analytical and simulation method for estimated residuals using the KS normality test. Results are partitioned out by model mis-specification (from left to right) and residual type (top to bottom).")
```

```{=tex}
\clearpage
\newpage
```

## Randomwalk

```{r, rw-results-theor osa-true, echo = FALSE, message = FALSE}

pval.df.true <- filter.true(pvals, "randomwalk",
                            type_ = "LMM",
                            test_ = "GOF.ks",
                       method.vec = res.methods)
pval.df.est <- filter.est(pvals, "randomwalk",
                            type_ = "LMM",
                            test_ = "GOF.ks",
                       method.vec = res.methods)
pval.df.true$misp <- factor(pval.df.true$misp,
         levels = c('correct', 'missre', 'hsk', 'm0', 'mispre'),
         labels = c("Correct",
                    "A: Missing RE",
                    "B: Heterosced.",
                    "C: Missing Drift",
                    "D: Misp RE" ))


pval.df.est$misp <- factor(pval.df.est$misp,
        levels = c('correct', 'missre', 'hsk', 'm0', 'mispre'),
         labels = c("Correct",
                    "A: Missing RE",
                    "B: Heterosced.",
                    "C: Missing Drift",
                    "D: Misp RE" ))


tbl.err.pow(pval.df.true, 
        caption = "Randomwalk Model. Type I error rates and Power evaluated for each analytical and simulation method for theoretical residuals using the KS normality test. Results are partitioned out by model mis-specification (from left to right) and residual type (top to bottom).")
```

```{r, rw-results-est osa-true, echo = FALSE, message = FALSE}

tbl.err.pow(pval.df.est, 
        caption = "Randomwalk Model. Type I error rates and Power evaluated for each analytical and simulation method for estimated residuals using the KS normality test. Results are partitioned out by model mis-specification (from left to right) and residual type (top to bottom).")
```



```{=tex}
\clearpage
\newpage
```

## Spatial

```{r, spatial-results-theor, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 8}

pval.df.true <- filter.true(pvals, "spatial",
                            type_ = "LMM",
                            test_ = "GOF.ks",
                       method.vec = res.methods)
pval.df.est <- filter.est(pvals, "spatial",
                            type_ = "LMM",
                            test_ = "GOF.ks",
                       method.vec = res.methods)

pval.df.true$misp <- factor(pval.df.true$misp,
         levels = c('correct', 'missre', 'ln-error', 'mispre'),
         labels = c("Correct",
                    "A: Missing RE",
                    "B: Lognorm error",
                    "C: Misp RE" ))

pval.df.est$misp <- factor(pval.df.est$misp,
         levels = c('correct', 'missre', 'ln-error', 'mispre'),
         labels = c("Correct",
                    "A: Missing RE",
                    "B: Lognorm error",
                    "C: Misp RE" ))
  

tbl.err.pow(pval.df.true, 
        caption = "Spatial Model. Type I error rates and Power evaluated for each analytical and simulation method for theoretical residuals using the KS normality test. Results are partitioned out by model mis-specification (from left to right) and residual type (top to bottom).")
```

```{r, spatial-results-est, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 8}

tbl.err.pow(pval.df.est, 
        caption = "Spatial Model. Type I error rates and Power evaluated for each analytical and simulation method for estimated residuals using the KS normality test. Results are partitioned out by model mis-specification (from left to right) and residual type (top to bottom).")
```

\input{"tables/tbl-1.tex"}

